sudo: required

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull $DOCKER_ORGANIZATION/rpi-debian-swig:latest
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build --build-arg DOCKER_ORGANIZATION=$DOCKER_ORGANIZATION -t rpi-debian-casadi .
  - docker tag rpi-debian-casadi $DOCKER_ORGANIZATION/rpi-debian-casadi:latest

script:
  - docker push $DOCKER_ORGANIZATION/rpi-debian-casadi:latest
