sudo: required

services:
  - docker

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker pull $DOCKER_USERNAME/rpi-debian-swig:latest
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build --build-arg DOCKER_USERNAME=$DOCKER_USERNAME -t rpi-debian-casadi .
  - docker tag rpi-debian-casadi $DOCKER_USERNAME/rpi-debian-casadi:latest

script:
  - docker push $DOCKER_USERNAME/rpi-debian-casadi:latest
