sudo: required

services:
  - docker

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker pull resin/raspberrypi3-debian:stretch
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t rpi-debian-casadi .
  - docker tag rpi-debian-casadi $DOCKER_USERNAME/rpi-debian-casadi:latest

script:
  - docker push $DOCKER_USERNAME/rpi-debian-casadi:latest
